### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by gcshri** [fidelisa/flutter_plugins#4]
Using the following in pubspec.yaml.

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  firebase_admob: "^0.5.4+1"
  redux: "^3.0.0"
  flutter_redux: "^0.5.0"
  flutter_firebase_ui: "^0.0.4"

```

Build returns this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```
Seems related to:

https://github.com/flutter/flutter/issues/13784
